// A4EC_OutputIds.h — AUTO-GENERATED by Tools/gen_a4ec/gen_a4ec.py
// DO NOT EDIT — regenerate using: python Tools/gen_a4ec/gen_a4ec.py
// DCS-BIOS source: DCS-BIOS v0.11.4 (DCS-BIOS_v0.11.4.zip)
// Generated:       2026-05-23T22:53:21Z
// Output count:    313

#pragma once

// Output address and mask constants for A-4E-C cockpit indicators and gauges.
// Constant names match the DCS-BIOS published identifiers exactly — the same
// names shown in Bort and other DCS-BIOS debug tools.
//
// For each output, two constants are defined:
//   <address_mask_shift_identifier>   — uint16_t DCS-BIOS output address
//   <address_mask_identifier> (_AM)   — uint16_t bitmask for the relevant bits
//
// Usage with LED:
//   OpenSkyhawk::LED warn(A_4E_C_MASTER_CAUTION, A_4E_C_MASTER_CAUTION_AM, pin);

#define A_4E_C_ACCEL_CUR                             0x8442  // Accelerometer
#define A_4E_C_ACCEL_CUR_AM                          0xffff

#define A_4E_C_ACCEL_MAX                             0x8444  // Accelerometer Max
#define A_4E_C_ACCEL_MAX_AM                          0xffff

#define A_4E_C_ACCEL_MIN                             0x8446  // Accelerometer Min
#define A_4E_C_ACCEL_MIN_AM                          0xffff

#define A_4E_C_ACCEL_RESET                           0x850e  // Reset Accelerometer
#define A_4E_C_ACCEL_RESET_AM                        0x2000

#define A_4E_C_ADI_HDG                               0x844e  // ADI Heading
#define A_4E_C_ADI_HDG_AM                            0xffff

#define A_4E_C_ADI_OFF                               0x8450  // ADI Off
#define A_4E_C_ADI_OFF_AM                            0xffff

#define A_4E_C_ADI_PITCH                             0x844a  // ADI Pitch
#define A_4E_C_ADI_PITCH_AM                          0xffff

#define A_4E_C_ADI_ROLL                              0x844c  // ADI Roll
#define A_4E_C_ADI_ROLL_AM                           0xffff

#define A_4E_C_ADI_SLIP                              0x8452  // ADI Slip
#define A_4E_C_ADI_SLIP_AM                           0xffff

#define A_4E_C_ADI_TURN                              0x8454  // ADI Turn
#define A_4E_C_ADI_TURN_AM                           0xffff

#define A_4E_C_AFCS_1N2                              0x854c  // AFCS 1-N-2 Guard
#define A_4E_C_AFCS_1N2_AM                           0x0018

#define A_4E_C_AFCS_1N2_COVER                        0x854c  // AFCS 1-N-2 Guard Cover
#define A_4E_C_AFCS_1N2_COVER_AM                     0x0004

#define A_4E_C_AFCS_AIL_TRIM                         0x8508  // AFCS Aileron Trim
#define A_4E_C_AFCS_AIL_TRIM_AM                      0x0004

#define A_4E_C_AFCS_ALT                              0x8508  // AFCS Altitude Hold
#define A_4E_C_AFCS_ALT_AM                           0x0001

#define A_4E_C_AFCS_ENGAGE                           0x8502  // AFCS Engage
#define A_4E_C_AFCS_ENGAGE_AM                        0x4000

#define A_4E_C_AFCS_HDG_100S                         0x8476  // AFCS Heading 100's
#define A_4E_C_AFCS_HDG_100S_AM                      0xffff

#define A_4E_C_AFCS_HDG_10S                          0x8478  // AFCS Heading 10's
#define A_4E_C_AFCS_HDG_10S_AM                       0xffff

#define A_4E_C_AFCS_HDG_1S                           0x847a  // AFCS Heading 1's
#define A_4E_C_AFCS_HDG_1S_AM                        0xffff

#define A_4E_C_AFCS_HDG_SEL                          0x8502  // AFCS Preselect Heading
#define A_4E_C_AFCS_HDG_SEL_AM                       0x8000

#define A_4E_C_AFCS_HDG_SET                          0x850a  // AFCS Heading Selector
#define A_4E_C_AFCS_HDG_SET_AM                       0xffff

#define A_4E_C_AFCS_PITCH                            0x8552  // AFCS Pitch Gauge
#define A_4E_C_AFCS_PITCH_AM                         0xffff

#define A_4E_C_AFCS_ROLL                             0x854e  // AFCS Roll Gauge
#define A_4E_C_AFCS_ROLL_AM                          0xffff

#define A_4E_C_AFCS_STAB_AUG                         0x8508  // AFCS Stability Aug
#define A_4E_C_AFCS_STAB_AUG_AM                      0x0002

#define A_4E_C_AFCS_STBY                             0x8502  // AFCS Standby
#define A_4E_C_AFCS_STBY_AM                          0x2000

#define A_4E_C_AFCS_YAW                              0x8550  // AFCS Yaw Gauge
#define A_4E_C_AFCS_YAW_AM                           0xffff

#define A_4E_C_ALT_ADJ_000N                          0x843a  // Altimeter Adjustment xxxN
#define A_4E_C_ALT_ADJ_000N_AM                       0xffff

#define A_4E_C_ALT_ADJ_00N0                          0x8438  // Altimeter Adjustment xxNx
#define A_4E_C_ALT_ADJ_00N0_AM                       0xffff

#define A_4E_C_ALT_ADJ_NN00                          0x8436  // Altimeter Adjustment NNxx
#define A_4E_C_ALT_ADJ_NN00_AM                       0xffff

#define A_4E_C_ALT_PRESS_KNB                         0x8516  // Altimeter Setting
#define A_4E_C_ALT_PRESS_KNB_AM                      0xffff

#define A_4E_C_AOA_G                                 0x8458  // Angle Of Attack
#define A_4E_C_AOA_G_AM                              0xffff

#define A_4E_C_AOA_GREEN                             0x8470  // AOA Indexer (green)
#define A_4E_C_AOA_GREEN_AM                          0x0001

#define A_4E_C_AOA_INDEX_DIM                         0x851a  // AOA Indexer Dimming Wheel
#define A_4E_C_AOA_INDEX_DIM_AM                      0xffff

#define A_4E_C_AOA_RED                               0x8470  // AOA Indexer (red)
#define A_4E_C_AOA_RED_AM                            0x0004

#define A_4E_C_AOA_YELLOW                            0x8470  // AOA Indexer (yellow)
#define A_4E_C_AOA_YELLOW_AM                         0x0002

#define A_4E_C_APC_ENABLE                            0x8508  // APC
#define A_4E_C_APC_ENABLE_AM                         0x0018

#define A_4E_C_APC_LIGHT                             0x8470  // APC Indicator Light (red)
#define A_4E_C_APC_LIGHT_AM                          0x0010

#define A_4E_C_APG53A_BOTTOMRANGE                    0x8474  // Radar Plan Range
#define A_4E_C_APG53A_BOTTOMRANGE_AM                 0xffff

#define A_4E_C_APG53A_GLOW                           0x84de  // Radar Glow Light (green)
#define A_4E_C_APG53A_GLOW_AM                        0xffff

#define A_4E_C_APG53A_LEFTRANGE                      0x8472  // Radar Profile Range
#define A_4E_C_APG53A_LEFTRANGE_AM                   0xffff

#define A_4E_C_APN153_DRIFT_GAUGE                    0x847c  // Drift Gauge
#define A_4E_C_APN153_DRIFT_GAUGE_AM                 0xffff

#define A_4E_C_APN153_MEMORYLIGHT                    0x8470  // Memory Light (yellow)
#define A_4E_C_APN153_MEMORYLIGHT_AM                 0x0100

#define A_4E_C_APN153_SPEED_00X                      0x8482  // Speed nnX
#define A_4E_C_APN153_SPEED_00X_AM                   0xffff

#define A_4E_C_APN153_SPEED_0X0                      0x8480  // Speed nXn
#define A_4E_C_APN153_SPEED_0X0_AM                   0xffff

#define A_4E_C_APN153_SPEED_X00                      0x847e  // Speed Xnn
#define A_4E_C_APN153_SPEED_X00_AM                   0xffff

#define A_4E_C_APS_COLD_STD_HOT                      0x8508  // APC
#define A_4E_C_APS_COLD_STD_HOT_AM                   0x0060

#define A_4E_C_ARC51_FREQ_000XX                      0x84d2  // Frequency nnnXX
#define A_4E_C_ARC51_FREQ_000XX_AM                   0xffff

#define A_4E_C_ARC51_FREQ_00X00                      0x84d0  // Frequency nnXnn
#define A_4E_C_ARC51_FREQ_00X00_AM                   0xffff

#define A_4E_C_ARC51_FREQ_10MHZ                      0x853a  // ARC-51 UHF Manual Frequency 10 MHz
#define A_4E_C_ARC51_FREQ_10MHZ_AM                   0x03e0

#define A_4E_C_ARC51_FREQ_1MHZ                       0x853a  // ARC-51 UHF Manual Frequency 1 MHz
#define A_4E_C_ARC51_FREQ_1MHZ_AM                    0x3c00

#define A_4E_C_ARC51_FREQ_50KHZ                      0x853e  // ARC-51 UHF Manual Frequency 50 kHz
#define A_4E_C_ARC51_FREQ_50KHZ_AM                   0x001f

#define A_4E_C_ARC51_FREQ_PRE                        0x853a  // ARC-51 UHF Preset Channel Selector
#define A_4E_C_ARC51_FREQ_PRE_AM                     0x001f

#define A_4E_C_ARC51_FREQ_PRESET                     0x84d4  // Frequency Preset
#define A_4E_C_ARC51_FREQ_PRESET_AM                  0xffff

#define A_4E_C_ARC51_FREQ_XX000                      0x84ce  // Frequency XXnnn
#define A_4E_C_ARC51_FREQ_XX000_AM                   0xffff

#define A_4E_C_ARC51_MODE                            0x853a  // ARC-51 UHF Mode
#define A_4E_C_ARC51_MODE_AM                         0xc000

#define A_4E_C_ARC51_SQUELCH                         0x8532  // ARC-51 UHF Squelch Disable
#define A_4E_C_ARC51_SQUELCH_AM                      0x4000

#define A_4E_C_ARC51_VOL                             0x853c  // ARC-51 UHF Volume
#define A_4E_C_ARC51_VOL_AM                          0xffff

#define A_4E_C_ARC51_XMIT_MODE                       0x8532  // ARC-51 UHF Frequency Mode
#define A_4E_C_ARC51_XMIT_MODE_AM                    0x3000

#define A_4E_C_ARM_BOMB                              0x8500  // Bomb arm switch
#define A_4E_C_ARM_BOMB_AM                           0x0018

#define A_4E_C_ARM_EMERG_SEL                         0x8500  // Emergency Release Selector
#define A_4E_C_ARM_EMERG_SEL_AM                      0x0007

#define A_4E_C_ARM_FUNC_SEL                          0x8500  // Function Selector
#define A_4E_C_ARM_FUNC_SEL_AM                       0x1c00

#define A_4E_C_ARM_GUN                               0x84ea  // Guns Switch
#define A_4E_C_ARM_GUN_AM                            0x8000

#define A_4E_C_ARM_MASTER                            0x8500  // Master Armament
#define A_4E_C_ARM_MASTER_AM                         0x4000

#define A_4E_C_ARM_STATION1                          0x8500  // Station 1 select
#define A_4E_C_ARM_STATION1_AM                       0x0020

#define A_4E_C_ARM_STATION2                          0x8500  // Station 2 select
#define A_4E_C_ARM_STATION2_AM                       0x0040

#define A_4E_C_ARM_STATION3                          0x8500  // Station 3 select
#define A_4E_C_ARM_STATION3_AM                       0x0080

#define A_4E_C_ARM_STATION4                          0x8500  // Station 4 select
#define A_4E_C_ARM_STATION4_AM                       0x0100

#define A_4E_C_ARM_STATION5                          0x8500  // Station 5 select
#define A_4E_C_ARM_STATION5_AM                       0x0200

#define A_4E_C_ASN41_LAT_SLEW                        0x8544  // ASN-41 Destination - Latitude Slew
#define A_4E_C_ASN41_LAT_SLEW_AM                     0x0060

#define A_4E_C_ASN41_LON_SLEW                        0x8544  // ASN-41 Destination - Longitude Slew
#define A_4E_C_ASN41_LON_SLEW_AM                     0x0180

#define A_4E_C_ASN41_MAGVAR_0000X                    0x84c4  // MagVar nnnnX
#define A_4E_C_ASN41_MAGVAR_0000X_AM                 0xffff

#define A_4E_C_ASN41_MAGVAR_000X0                    0x84c2  // MagVar nnnXn
#define A_4E_C_ASN41_MAGVAR_000X0_AM                 0xffff

#define A_4E_C_ASN41_MAGVAR_00X00                    0x84c0  // MagVar nnXnn
#define A_4E_C_ASN41_MAGVAR_00X00_AM                 0xffff

#define A_4E_C_ASN41_MAGVAR_0X000                    0x84be  // MagVar nXnnn
#define A_4E_C_ASN41_MAGVAR_0X000_AM                 0xffff

#define A_4E_C_ASN41_MAGVAR_BTN                      0x8522  // ASN-41 Magnetic Variation Button
#define A_4E_C_ASN41_MAGVAR_BTN_AM                   0x0400

#define A_4E_C_ASN41_MAGVAR_KNB                      0x852c  // ASN-41 Magnetic Variation Knob
#define A_4E_C_ASN41_MAGVAR_KNB_AM                   0xffff

#define A_4E_C_ASN41_MAGVAR_X0000                    0x84bc  // MagVar Xnnnn
#define A_4E_C_ASN41_MAGVAR_X0000_AM                 0xffff

#define A_4E_C_ASN41_WINDDIR_00X                     0x84ba  // Wind Direction nnX
#define A_4E_C_ASN41_WINDDIR_00X_AM                  0xffff

#define A_4E_C_ASN41_WINDDIR_0X0                     0x84b8  // Wind Direction nXn
#define A_4E_C_ASN41_WINDDIR_0X0_AM                  0xffff

#define A_4E_C_ASN41_WINDDIR_BTN                     0x8522  // ASN-41 Wind Bearing Button
#define A_4E_C_ASN41_WINDDIR_BTN_AM                  0x1000

#define A_4E_C_ASN41_WINDDIR_KNB                     0x8530  // ASN-41 Wind Direction Knob
#define A_4E_C_ASN41_WINDDIR_KNB_AM                  0xffff

#define A_4E_C_ASN41_WINDDIR_X00                     0x84b6  // Wind Direction Xnn
#define A_4E_C_ASN41_WINDDIR_X00_AM                  0xffff

#define A_4E_C_ASN41_WINDSPEED_00X                   0x84b4  // Windspeed nnX
#define A_4E_C_ASN41_WINDSPEED_00X_AM                0xffff

#define A_4E_C_ASN41_WINDSPEED_0X0                   0x84b2  // Windspeed nXn
#define A_4E_C_ASN41_WINDSPEED_0X0_AM                0xffff

#define A_4E_C_ASN41_WINDSPEED_BTN                   0x8522  // ASN-41 Wind Speed Button
#define A_4E_C_ASN41_WINDSPEED_BTN_AM                0x0800

#define A_4E_C_ASN41_WINDSPEED_KNB                   0x852e  // ASN-41 Wind Speed Knob
#define A_4E_C_ASN41_WINDSPEED_KNB_AM                0xffff

#define A_4E_C_ASN41_WINDSPEED_X00                   0x84b0  // Windspeed Xnn
#define A_4E_C_ASN41_WINDSPEED_X00_AM                0xffff

#define A_4E_C_ATTGYRO_STBY_HORIZ                    0x8418  // SAI Horizon
#define A_4E_C_ATTGYRO_STBY_HORIZ_AM                 0xffff

#define A_4E_C_ATTGYRO_STBY_OFF                      0x841e  // SAI Off
#define A_4E_C_ATTGYRO_STBY_OFF_AM                   0xffff

#define A_4E_C_ATTGYRO_STBY_PITCH                    0x841a  // SAI Pitch
#define A_4E_C_ATTGYRO_STBY_PITCH_AM                 0xffff

#define A_4E_C_ATTGYRO_STBY_ROLL                     0x841c  // SAI Roll
#define A_4E_C_ATTGYRO_STBY_ROLL_AM                  0xffff

#define A_4E_C_AWRS_DROP_INT                         0x8504  // AWRS Drop Interval
#define A_4E_C_AWRS_DROP_INT_AM                      0xffff

#define A_4E_C_AWRS_MODE                             0x8502  // AWRS mode
#define A_4E_C_AWRS_MODE_AM                          0x0070

#define A_4E_C_AWRS_MULTI                            0x8500  // AWRS Multiplier
#define A_4E_C_AWRS_MULTI_AM                         0x2000

#define A_4E_C_AWRS_POWER                            0x8470  // AWRS Power Indicator Light (yellow)
#define A_4E_C_AWRS_POWER_AM                         0x0008

#define A_4E_C_AWRS_QUANT                            0x8502  // AWRS Quantity Selector
#define A_4E_C_AWRS_QUANT_AM                         0x000f

#define A_4E_C_BDHI_DME_00X                          0x846a  // BDHI nnX
#define A_4E_C_BDHI_DME_00X_AM                       0xffff

#define A_4E_C_BDHI_DME_0X0                          0x8468  // BDHI nXn
#define A_4E_C_BDHI_DME_0X0_AM                       0xffff

#define A_4E_C_BDHI_DME_FLAG                         0x8464  // BDHI Flag
#define A_4E_C_BDHI_DME_FLAG_AM                      0xffff

#define A_4E_C_BDHI_DME_X00                          0x8466  // BDHI Xnn
#define A_4E_C_BDHI_DME_X00_AM                       0xffff

#define A_4E_C_BDHI_HDG                              0x845e  // BDHI Heading
#define A_4E_C_BDHI_HDG_AM                           0xffff

#define A_4E_C_BDHI_ILS_GS                           0x846c  // BDHI ILS GS
#define A_4E_C_BDHI_ILS_GS_AM                        0xffff

#define A_4E_C_BDHI_ILS_LOC                          0x846e  // BDHI ILS LOC
#define A_4E_C_BDHI_ILS_LOC_AM                       0xffff

#define A_4E_C_BDHI_MODE                             0x8502  // BDHI mode
#define A_4E_C_BDHI_MODE_AM                          0x0300

#define A_4E_C_BDHI_NEEDLE1                          0x8460  // BDHI Needle 1
#define A_4E_C_BDHI_NEEDLE1_AM                       0xffff

#define A_4E_C_BDHI_NEEDLE2                          0x8462  // BDHI Needle 2
#define A_4E_C_BDHI_NEEDLE2_AM                       0xffff

#define A_4E_C_CABIN_ALT                             0x843c  // Cabin Altitude
#define A_4E_C_CABIN_ALT_AM                          0xffff

#define A_4E_C_CABIN_PRESS                           0x8544  // Cabin Pressure Switch
#define A_4E_C_CABIN_PRESS_AM                        0x0001

#define A_4E_C_CABIN_TEMP                            0x8546  // Cabin Temp Knob
#define A_4E_C_CABIN_TEMP_AM                         0xffff

#define A_4E_C_CANOPY_POS                            0x84ec  // Canopy Position
#define A_4E_C_CANOPY_POS_AM                         0xffff

#define A_4E_C_CANOPY_SW                             0x8508  // Canopy
#define A_4E_C_CANOPY_SW_AM                          0x2000

#define A_4E_C_CM_ADJ1                               0x84fc  // CM Bank 1 Adjust
#define A_4E_C_CM_ADJ1_AM                            0xffff

#define A_4E_C_CM_ADJ2                               0x84fe  // CM Bank 2 Adjust
#define A_4E_C_CM_ADJ2_AM                            0xffff

#define A_4E_C_CM_AUTO                               0x84ea  // CM Auto Pushbutton
#define A_4E_C_CM_AUTO_AM                            0x2000

#define A_4E_C_CM_BANK                               0x84ea  // CM Bank Select
#define A_4E_C_CM_BANK_AM                            0x1800

#define A_4E_C_CM_BANK1_0X                           0x84c8  // CM Bank 1 1's
#define A_4E_C_CM_BANK1_0X_AM                        0xffff

#define A_4E_C_CM_BANK1_X0                           0x84c6  // CM Bank 1 10's
#define A_4E_C_CM_BANK1_X0_AM                        0xffff

#define A_4E_C_CM_BANK2_0X                           0x84cc  // CM Bank 2 1's
#define A_4E_C_CM_BANK2_0X_AM                        0xffff

#define A_4E_C_CM_BANK2_X0                           0x84ca  // CM Bank 2 10's
#define A_4E_C_CM_BANK2_X0_AM                        0xffff

#define A_4E_C_CM_PWR                                0x84ea  // CM Power Toggle
#define A_4E_C_CM_PWR_AM                             0x4000

#define A_4E_C_COMPASS_HDG                           0x8456  // Backup Compass
#define A_4E_C_COMPASS_HDG_AM                        0xffff

#define A_4E_C_CURRTIME_HOURS                        0x84e0  // Current Hours
#define A_4E_C_CURRTIME_HOURS_AM                     0xffff

#define A_4E_C_CURRTIME_MINS                         0x84e2  // Current Minutes
#define A_4E_C_CURRTIME_MINS_AM                      0xffff

#define A_4E_C_CURRTIME_SECS                         0x84e4  // Current Seconds
#define A_4E_C_CURRTIME_SECS_AM                      0xffff

#define A_4E_C_DEST_LAT_BTN                          0x8522  // ASN-41 Destination - Latitude Button
#define A_4E_C_DEST_LAT_BTN_AM                       0x0100

#define A_4E_C_DEST_LAT_KNB                          0x8528  // ASN-41 Destination - Latitude Knob
#define A_4E_C_DEST_LAT_KNB_AM                       0xffff

#define A_4E_C_DEST_LON_BTN                          0x8522  // ASN-41 Destination - Longitude Button
#define A_4E_C_DEST_LON_BTN_AM                       0x0200

#define A_4E_C_DEST_LON_KNB                          0x852a  // ASN-41 Destination - Longitude Knob
#define A_4E_C_DEST_LON_KNB_AM                       0xffff

#define A_4E_C_DOPPLER_MEM_TEST                      0x8512  // APN-153 Memory Light Test
#define A_4E_C_DOPPLER_MEM_TEST_AM                   0x8000

#define A_4E_C_DOPPLER_SEL                           0x8522  // APN-153 Doppler Radar Mode
#define A_4E_C_DOPPLER_SEL_AM                        0x0007

#define A_4E_C_DROP_PRESS_REFUEL                     0x850e  // Drop Tanks Pressurization and Flight Refuel Switch
#define A_4E_C_DROP_PRESS_REFUEL_AM                  0x0060

#define A_4E_C_D_ADVISORY_DIVE                       0x8470  // Dive Light (yellow)
#define A_4E_C_D_ADVISORY_DIVE_AM                    0x0080

#define A_4E_C_D_ADVISORY_INRANGE                    0x8470  // In Range Light (yellow)
#define A_4E_C_D_ADVISORY_INRANGE_AM                 0x0020

#define A_4E_C_D_ADVISORY_SETRANGE                   0x8470  // Set Range Light (yellow)
#define A_4E_C_D_ADVISORY_SETRANGE_AM                0x0040

#define A_4E_C_D_ALT_100S                            0x8434  // Altimeter 100s
#define A_4E_C_D_ALT_100S_AM                         0xffff

#define A_4E_C_D_ALT_10K                             0x8430  // Altimeter 10k
#define A_4E_C_D_ALT_10K_AM                          0xffff

#define A_4E_C_D_ALT_1K                              0x8432  // Altimeter 1k
#define A_4E_C_D_ALT_1K_AM                           0xffff

#define A_4E_C_D_ALT_NEEDLE                          0x842e  // Altimeter needle
#define A_4E_C_D_ALT_NEEDLE_AM                       0xffff

#define A_4E_C_D_CONTHYD_CAUTION                     0x845c  // Control Hydraulics-Caution Ladder (yellow)
#define A_4E_C_D_CONTHYD_CAUTION_AM                  0x0002

#define A_4E_C_D_FLAPS_IND                           0x840e  // Flaps Indicator
#define A_4E_C_D_FLAPS_IND_AM                        0xffff

#define A_4E_C_D_FUEL                                0x840c  // Fuel Gauge
#define A_4E_C_D_FUEL_AM                             0xffff

#define A_4E_C_D_FUELBOOST_CAUTION                   0x845c  // Fuel Boost-Caution Ladder (yellow)
#define A_4E_C_D_FUELBOOST_CAUTION_AM                0x0001

#define A_4E_C_D_FUELTRANS_CAUTION                   0x845c  // Fuel Transfer-Caution Ladder (yellow)
#define A_4E_C_D_FUELTRANS_CAUTION_AM                0x0008

#define A_4E_C_D_FUEL_FLOW                           0x8406  // Fuel Flow
#define A_4E_C_D_FUEL_FLOW_AM                        0xffff

#define A_4E_C_D_GLARE_FIRE                          0x845c  // Glareshield Fire (red)
#define A_4E_C_D_GLARE_FIRE_AM                       0x2000

#define A_4E_C_D_GLARE_IFF                           0x845c  // Glareshield IFF (white)
#define A_4E_C_D_GLARE_IFF_AM                        0x1000

#define A_4E_C_D_GLARE_LABS                          0x845c  // Glareshield LABS (yellow)
#define A_4E_C_D_GLARE_LABS_AM                       0x0200

#define A_4E_C_D_GLARE_LAWS                          0x845c  // Glareshield LAWS (red)
#define A_4E_C_D_GLARE_LAWS_AM                       0x0400

#define A_4E_C_D_GLARE_OBST                          0x845c  // Glareshield OBST (yellow)
#define A_4E_C_D_GLARE_OBST_AM                       0x0800

#define A_4E_C_D_GLARE_WHEELS                        0x845c  // Glareshield Wheels (white)
#define A_4E_C_D_GLARE_WHEELS_AM                     0x0100

#define A_4E_C_D_GUNSIGHT_REFLECTOR                  0x845a  // Gunsight Reflector Elevation
#define A_4E_C_D_GUNSIGHT_REFLECTOR_AM               0xffff

#define A_4E_C_D_IAS_DEG                             0x8420  // IAS
#define A_4E_C_D_IAS_DEG_AM                          0xffff

#define A_4E_C_D_IAS_IDX                             0x8424  // IAS Index
#define A_4E_C_D_IAS_IDX_AM                          0xffff

#define A_4E_C_D_IAS_MACH_DEG                        0x8422  // Mach Disc
#define A_4E_C_D_IAS_MACH_DEG_AM                     0xffff

#define A_4E_C_D_MACH_IDX                            0x8426  // Mach Index
#define A_4E_C_D_MACH_IDX_AM                         0xffff

#define A_4E_C_D_OIL_LOW                             0x845c  // Oil Low Light (yellow)
#define A_4E_C_D_OIL_LOW_AM                          0x0080

#define A_4E_C_D_OXYGEN_LOW                          0x845c  // Oxygen Low (red)
#define A_4E_C_D_OXYGEN_LOW_AM                       0x4000

#define A_4E_C_D_OXYGEN_OFF                          0x8440  // Oxygen off flag
#define A_4E_C_D_OXYGEN_OFF_AM                       0xffff

#define A_4E_C_D_RADAR_ALT                           0x8428  // Radar Altimeter
#define A_4E_C_D_RADAR_ALT_AM                        0xffff

#define A_4E_C_D_RADAR_IDX                           0x842a  // Radar ALtimeter Indexer
#define A_4E_C_D_RADAR_IDX_AM                        0xffff

#define A_4E_C_D_RADAR_OFF                           0x842c  // Radar Altimeter Off flag
#define A_4E_C_D_RADAR_OFF_AM                        0xffff

#define A_4E_C_D_RADAR_WARN                          0x845c  // Radar Altitude Warning (red)
#define A_4E_C_D_RADAR_WARN_AM                       0x0040

#define A_4E_C_D_SPDBRK_CAUTION                      0x845c  // Speed Break-Caution Ladder (yellow)
#define A_4E_C_D_SPDBRK_CAUTION_AM                   0x0010

#define A_4E_C_D_SPOILER_CAUTION                     0x845c  // Spoiler-Caution Ladder (yellow)
#define A_4E_C_D_SPOILER_CAUTION_AM                  0x0020

#define A_4E_C_D_TAIL_HOOK                           0x8410  // Hook Indicator
#define A_4E_C_D_TAIL_HOOK_AM                        0xffff

#define A_4E_C_D_UTILHYD_CAUTION                     0x845c  // Utility Hydraulics-Caution Ladder (yellow)
#define A_4E_C_D_UTILHYD_CAUTION_AM                  0x0004

#define A_4E_C_ECM_APR25_PW                          0x853e  // APR/25 On/Off
#define A_4E_C_ECM_APR25_PW_AM                       0x0400

#define A_4E_C_ECM_APR27_LIGHT                       0x853e  // APR/27 Light
#define A_4E_C_ECM_APR27_LIGHT_AM                    0x2000

#define A_4E_C_ECM_APR27_PW                          0x853e  // APR/27 On/Off
#define A_4E_C_ECM_APR27_PW_AM                       0x0800

#define A_4E_C_ECM_APR27_TEST                        0x853e  // APR/27 Test
#define A_4E_C_ECM_APR27_TEST_AM                     0x1000

#define A_4E_C_ECM_AUDIO                             0x853e  // Audio APR/25 - APR/27
#define A_4E_C_ECM_AUDIO_AM                          0x0200

#define A_4E_C_ECM_GO_LIGHT                          0x8470  // ECM GO Light (green)
#define A_4E_C_ECM_GO_LIGHT_AM                       0x0800

#define A_4E_C_ECM_MSL_VOL                           0x8542  // MSL Volume (Outer Knob)
#define A_4E_C_ECM_MSL_VOL_AM                        0xffff

#define A_4E_C_ECM_NOGO_LIGHT                        0x8470  // ECM NO GO Light (red)
#define A_4E_C_ECM_NOGO_LIGHT_AM                     0x1000

#define A_4E_C_ECM_PRF_VOL                           0x8540  // PRF Volume (Inner Knob)
#define A_4E_C_ECM_PRF_VOL_AM                        0xffff

#define A_4E_C_ECM_REC_LIGHT                         0x84ea  // ECM REC Light (red)
#define A_4E_C_ECM_REC_LIGHT_AM                      0x0001

#define A_4E_C_ECM_RPT_LIGHT                         0x8470  // ECM RPT Light (green)
#define A_4E_C_ECM_RPT_LIGHT_AM                      0x4000

#define A_4E_C_ECM_SAM_LIGHT                         0x8470  // ECM SAM Light (red)
#define A_4E_C_ECM_SAM_LIGHT_AM                      0x2000

#define A_4E_C_ECM_SEL                               0x853e  // AN/APR-25 Selector Knob
#define A_4E_C_ECM_SEL_AM                            0xc000

#define A_4E_C_ECM_STBY_LIGHT                        0x8470  // ECM STBY Light (yellow)
#define A_4E_C_ECM_STBY_LIGHT_AM                     0x8000

#define A_4E_C_ECM_TEST_LIGHT                        0x8470  // ECM Test Light (white)
#define A_4E_C_ECM_TEST_LIGHT_AM                     0x0400

#define A_4E_C_EGT_C                                 0x8404  // EGT
#define A_4E_C_EGT_C_AM                              0xffff

#define A_4E_C_EMERG_BOMB_REL                        0x853e  // Emergency Bomb Release
#define A_4E_C_EMERG_BOMB_REL_AM                     0x0020

#define A_4E_C_EMERG_GEAR_REL                        0x8532  // Emergency Gear Release
#define A_4E_C_EMERG_GEAR_REL_AM                     0x8000

#define A_4E_C_EMERG_GEN_BYPASS                      0x853e  // Emergency Generator Bypass/Normal
#define A_4E_C_EMERG_GEN_BYPASS_AM                   0x0080

#define A_4E_C_EMERG_GEN_DEPLOY                      0x853e  // Emergency Generator Deploy
#define A_4E_C_EMERG_GEN_DEPLOY_AM                   0x0040

#define A_4E_C_EMERG_TRANS_FUEL_DUMP                 0x850e  // Emergency Transfer and Wing Fuel Dump Switch
#define A_4E_C_EMERG_TRANS_FUEL_DUMP_AM              0x0180

#define A_4E_C_EXT_HOOK                              0x854a  // Hook
#define A_4E_C_EXT_HOOK_AM                           0xffff

#define A_4E_C_EXT_POSITION_LIGHT_LEFT               0x8544  // Left Position Light (red)
#define A_4E_C_EXT_POSITION_LIGHT_LEFT_AM            0x0200

#define A_4E_C_EXT_POSITION_LIGHT_RIGHT              0x8544  // Right Position Light (green)
#define A_4E_C_EXT_POSITION_LIGHT_RIGHT_AM           0x0400

#define A_4E_C_EXT_SPEED_BRAKES                      0x8548  // Speed Brakes
#define A_4E_C_EXT_SPEED_BRAKES_AM                   0xffff

#define A_4E_C_EXT_STROBE_BOTTOM                     0x8544  // Bottom Strobe Light (red)
#define A_4E_C_EXT_STROBE_BOTTOM_AM                  0x2000

#define A_4E_C_EXT_STROBE_TOP                        0x8544  // Top Strobe Light (red)
#define A_4E_C_EXT_STROBE_TOP_AM                     0x1000

#define A_4E_C_EXT_TAIL_LIGHT                        0x8544  // Tail Light (white)
#define A_4E_C_EXT_TAIL_LIGHT_AM                     0x0800

#define A_4E_C_EXT_TAXI_LIGHT                        0x8544  // Taxi Light (white)
#define A_4E_C_EXT_TAXI_LIGHT_AM                     0x4000

#define A_4E_C_EXT_WOW_LEFT                          0x854c  // Weight ON Wheels Left Gear
#define A_4E_C_EXT_WOW_LEFT_AM                       0x0002

#define A_4E_C_EXT_WOW_NOSE                          0x8544  // Weight ON Wheels Nose Gear
#define A_4E_C_EXT_WOW_NOSE_AM                       0x8000

#define A_4E_C_EXT_WOW_RIGHT                         0x854c  // Weight ON Wheels Right Gear
#define A_4E_C_EXT_WOW_RIGHT_AM                      0x0001

#define A_4E_C_FLAPS                                 0x8508  // Flaps Lever
#define A_4E_C_FLAPS_AM                              0xc000

#define A_4E_C_FUEL_CONTROL                          0x850e  // Fuel Control Switch
#define A_4E_C_FUEL_CONTROL_AM                       0x0200

#define A_4E_C_FUEL_EXT_BTN                          0x8512  // Show EXT Fuel
#define A_4E_C_FUEL_EXT_BTN_AM                       0x0002

#define A_4E_C_FUEL_TRANS                            0x8554  // Fuel Transfer Bypass/Normal
#define A_4E_C_FUEL_TRANS_AM                         0x0002

#define A_4E_C_GEAR_HANDLE                           0x8508  // Landing Gear Handle
#define A_4E_C_GEAR_HANDLE_AM                        0x0080

#define A_4E_C_GEAR_LEFT                             0x8414  // Left Gear Indicator
#define A_4E_C_GEAR_LEFT_AM                          0xffff

#define A_4E_C_GEAR_LIGHT                            0x845c  // Landing Gear Light (red)
#define A_4E_C_GEAR_LIGHT_AM                         0x8000

#define A_4E_C_GEAR_NOSE                             0x8412  // Nose Gear Indicator
#define A_4E_C_GEAR_NOSE_AM                          0xffff

#define A_4E_C_GEAR_RIGHT                            0x8416  // Right Gear Indicator
#define A_4E_C_GEAR_RIGHT_AM                         0xffff

#define A_4E_C_GUNPOD_C                              0x84ea  // Gunpod Station CTR Switch
#define A_4E_C_GUNPOD_C_AM                           0x0200

#define A_4E_C_GUNPOD_CLEAR                          0x84ea  // Gunpod
#define A_4E_C_GUNPOD_CLEAR_AM                       0x00c0

#define A_4E_C_GUNPOD_L                              0x84ea  // Gunpod Station LH Switch
#define A_4E_C_GUNPOD_L_AM                           0x0100

#define A_4E_C_GUNPOD_R                              0x84ea  // Gunpod Station RH Switch
#define A_4E_C_GUNPOD_R_AM                           0x0400

#define A_4E_C_GUNSIGHT_BRIGHT                       0x851c  // Gunsight Light Control
#define A_4E_C_GUNSIGHT_BRIGHT_AM                    0xffff

#define A_4E_C_GUNSIGHT_DAY_NIGHT                    0x8512  // Gunsight Day/Night Switch
#define A_4E_C_GUNSIGHT_DAY_NIGHT_AM                 0x0010

#define A_4E_C_GUNSIGHT_KNB                          0x851e  // Gunsight Elevation Control
#define A_4E_C_GUNSIGHT_KNB_AM                       0xffff

#define A_4E_C_HARNESS_REEL_CONTR                    0x8544  // Shoulder Harness Inertia Reel Control
#define A_4E_C_HARNESS_REEL_CONTR_AM                 0x0008

#define A_4E_C_HOOK_HANDLE                           0x8508  // Landing Hook Handle
#define A_4E_C_HOOK_HANDLE_AM                        0x0100

#define A_4E_C_IAS_INDEX_BTN                         0x8512  // IAS Index Button
#define A_4E_C_IAS_INDEX_BTN_AM                      0x0008

#define A_4E_C_IAS_INDEX_KNB                         0x8518  // IAS Index Knob
#define A_4E_C_IAS_INDEX_KNB_AM                      0xffff

#define A_4E_C_JATO_ARM                              0x850e  // JATO ARM-OFF Switch
#define A_4E_C_JATO_ARM_AM                           0x0008

#define A_4E_C_JATO_JETT_SAFE                        0x850e  // JATO JETTISON-SAFE Switch
#define A_4E_C_JATO_JETT_SAFE_AM                     0x0010

#define A_4E_C_LIGHTS_CONSOLE                        0x84dc  // Console Lights (red)
#define A_4E_C_LIGHTS_CONSOLE_AM                     0xffff

#define A_4E_C_LIGHTS_FLOOD_RED                      0x84d8  // Red Flood Lights (red)
#define A_4E_C_LIGHTS_FLOOD_RED_AM                   0xffff

#define A_4E_C_LIGHTS_FLOOD_WHITE                    0x84d6  // White Flood Lights (white)
#define A_4E_C_LIGHTS_FLOOD_WHITE_AM                 0xffff

#define A_4E_C_LIGHTS_INSTRUMENTS                    0x84da  // Instrument Lights (red)
#define A_4E_C_LIGHTS_INSTRUMENTS_AM                 0xffff

#define A_4E_C_LIGHT_EXT_ANTICOLL                    0x8532  // Anti-Collision Lights
#define A_4E_C_LIGHT_EXT_ANTICOLL_AM                 0x0004

#define A_4E_C_LIGHT_EXT_FLASH_MODE                  0x8532  // Lighting Flash/Steady Mode
#define A_4E_C_LIGHT_EXT_FLASH_MODE_AM               0x0020

#define A_4E_C_LIGHT_EXT_FUSELAGE                    0x8532  // Fuselage Lights
#define A_4E_C_LIGHT_EXT_FUSELAGE_AM                 0x0018

#define A_4E_C_LIGHT_EXT_MASTER                      0x8522  // Master Lighting
#define A_4E_C_LIGHT_EXT_MASTER_AM                   0x6000

#define A_4E_C_LIGHT_EXT_NAV                         0x8532  // Navigation Lights
#define A_4E_C_LIGHT_EXT_NAV_AM                      0x00c0

#define A_4E_C_LIGHT_EXT_PROBE                       0x8532  // Probe Light
#define A_4E_C_LIGHT_EXT_PROBE_AM                    0x0003

#define A_4E_C_LIGHT_EXT_TAIL                        0x8532  // Tail Light
#define A_4E_C_LIGHT_EXT_TAIL_AM                     0x0300

#define A_4E_C_LIGHT_EXT_TAXI                        0x8522  // Taxi Light
#define A_4E_C_LIGHT_EXT_TAXI_AM                     0x8000

#define A_4E_C_LIGHT_INT_BRIGHT                      0x8532  // Console Light Intensity
#define A_4E_C_LIGHT_INT_BRIGHT_AM                   0x0c00

#define A_4E_C_LIGHT_INT_CONSOLE                     0x8536  // Console Lighting
#define A_4E_C_LIGHT_INT_CONSOLE_AM                  0xffff

#define A_4E_C_LIGHT_INT_FLOOD_WHT                   0x8538  // White FloodLight Control
#define A_4E_C_LIGHT_INT_FLOOD_WHT_AM                0xffff

#define A_4E_C_LIGHT_INT_INSTR                       0x8534  // Instrument Lighting
#define A_4E_C_LIGHT_INT_INSTR_AM                    0xffff

#define A_4E_C_LIQUID_O2                             0x843e  // Liquid Oxygen
#define A_4E_C_LIQUID_O2_AM                          0xffff

#define A_4E_C_MAN_FLIGHT_CONTROL                    0x853e  // Manual Flight Control Override
#define A_4E_C_MAN_FLIGHT_CONTROL_AM                 0x0100

#define A_4E_C_MAN_FUEL_OFF_CATCH                    0x850e  // Manual Fuel Shutoff Catch
#define A_4E_C_MAN_FUEL_OFF_CATCH_AM                 0x0800

#define A_4E_C_MAN_FUEL_OFF_LV                       0x850e  // Manual Fuel Shutoff Lever
#define A_4E_C_MAN_FUEL_OFF_LV_AM                    0x0400

#define A_4E_C_MASTER_TEST                           0x8512  // Master Test
#define A_4E_C_MASTER_TEST_AM                        0x0004

#define A_4E_C_MCL_CHAN_SEL                          0x854c  // MCL Channel Selector
#define A_4E_C_MCL_CHAN_SEL_AM                       0x03e0

#define A_4E_C_MCL_PWR                               0x854c  // MCL Power
#define A_4E_C_MCL_PWR_AM                            0x0c00

#define A_4E_C_MISSILE_VOL                           0x8506  // Missile Volume Knob
#define A_4E_C_MISSILE_VOL_AM                        0xffff

#define A_4E_C_NAV_CURPOS_LAT_0000X                  0x848c  // Current Latitude nnnnX
#define A_4E_C_NAV_CURPOS_LAT_0000X_AM               0xffff

#define A_4E_C_NAV_CURPOS_LAT_000X0                  0x848a  // Current Latitude nnnXn
#define A_4E_C_NAV_CURPOS_LAT_000X0_AM               0xffff

#define A_4E_C_NAV_CURPOS_LAT_00X00                  0x8488  // Current Latitude nnXnn
#define A_4E_C_NAV_CURPOS_LAT_00X00_AM               0xffff

#define A_4E_C_NAV_CURPOS_LAT_0X000                  0x8486  // Current Latitude nXnnn
#define A_4E_C_NAV_CURPOS_LAT_0X000_AM               0xffff

#define A_4E_C_NAV_CURPOS_LAT_X0000                  0x8484  // Current Latitude Xnnnn
#define A_4E_C_NAV_CURPOS_LAT_X0000_AM               0xffff

#define A_4E_C_NAV_CURPOS_LON_00000X                 0x8498  // Current Longitude nnnnnX
#define A_4E_C_NAV_CURPOS_LON_00000X_AM              0xffff

#define A_4E_C_NAV_CURPOS_LON_0000X0                 0x8496  // Current Longitude nnnnXn
#define A_4E_C_NAV_CURPOS_LON_0000X0_AM              0xffff

#define A_4E_C_NAV_CURPOS_LON_000X00                 0x8494  // Current Longitude nnnXnn
#define A_4E_C_NAV_CURPOS_LON_000X00_AM              0xffff

#define A_4E_C_NAV_CURPOS_LON_00X000                 0x8492  // Current Longitude nnXnnn
#define A_4E_C_NAV_CURPOS_LON_00X000_AM              0xffff

#define A_4E_C_NAV_CURPOS_LON_0X0000                 0x8490  // Current Longitude nXnnnn
#define A_4E_C_NAV_CURPOS_LON_0X0000_AM              0xffff

#define A_4E_C_NAV_CURPOS_LON_X00000                 0x848e  // Current Longitude Xnnnnn
#define A_4E_C_NAV_CURPOS_LON_X00000_AM              0xffff

#define A_4E_C_NAV_DEAD                              0x8554  // Navigation Dead Reckoning/Doppler
#define A_4E_C_NAV_DEAD_AM                           0x0001

#define A_4E_C_NAV_DEST_LAT_0000X                    0x84a2  // Destination Latitude nnnnX
#define A_4E_C_NAV_DEST_LAT_0000X_AM                 0xffff

#define A_4E_C_NAV_DEST_LAT_000X0                    0x84a0  // Destination Latitude nnnXn
#define A_4E_C_NAV_DEST_LAT_000X0_AM                 0xffff

#define A_4E_C_NAV_DEST_LAT_00X00                    0x849e  // Destination Latitude nnXnn
#define A_4E_C_NAV_DEST_LAT_00X00_AM                 0xffff

#define A_4E_C_NAV_DEST_LAT_0X000                    0x849c  // Destination Latitude nXnnn
#define A_4E_C_NAV_DEST_LAT_0X000_AM                 0xffff

#define A_4E_C_NAV_DEST_LAT_X0000                    0x849a  // Destination Latitude Xnnnn
#define A_4E_C_NAV_DEST_LAT_X0000_AM                 0xffff

#define A_4E_C_NAV_DEST_LON_00000X                   0x84ae  // Destination Longitude nnnnnX
#define A_4E_C_NAV_DEST_LON_00000X_AM                0xffff

#define A_4E_C_NAV_DEST_LON_0000X0                   0x84ac  // Destination Longitude nnnnXn
#define A_4E_C_NAV_DEST_LON_0000X0_AM                0xffff

#define A_4E_C_NAV_DEST_LON_000X00                   0x84aa  // Destination Longitude nnnXnn
#define A_4E_C_NAV_DEST_LON_000X00_AM                0xffff

#define A_4E_C_NAV_DEST_LON_00X000                   0x84a8  // Destination Longitude nnXnnn
#define A_4E_C_NAV_DEST_LON_00X000_AM                0xffff

#define A_4E_C_NAV_DEST_LON_0X0000                   0x84a6  // Destination Longitude nXnnnn
#define A_4E_C_NAV_DEST_LON_0X0000_AM                0xffff

#define A_4E_C_NAV_DEST_LON_X00000                   0x84a4  // Destination Longitude Xnnnnn
#define A_4E_C_NAV_DEST_LON_X00000_AM                0xffff

#define A_4E_C_NAV_SEL                               0x8522  // ASN-41 Function Selector Switch
#define A_4E_C_NAV_SEL_AM                            0x0038

#define A_4E_C_OIL_PRESSURE                          0x8408  // Oil Pressure
#define A_4E_C_OIL_PRESSURE_AM                       0xffff

#define A_4E_C_OXY_SW                                0x850e  // Oxygen Switch
#define A_4E_C_OXY_SW_AM                             0x1000

#define A_4E_C_PPOS_LAT_BTN                          0x8522  // ASN-41 Present Position - Latitude Button
#define A_4E_C_PPOS_LAT_BTN_AM                       0x0040

#define A_4E_C_PPOS_LAT_KNB                          0x8524  // ASN-41 Present Position - Latitude Knob
#define A_4E_C_PPOS_LAT_KNB_AM                       0xffff

#define A_4E_C_PPOS_LON_BTN                          0x8522  // ASN-41 Present Position - Longitude Button
#define A_4E_C_PPOS_LON_BTN_AM                       0x0080

#define A_4E_C_PPOS_LON_KNB                          0x8526  // ASN-41 Present Position - Longitude Knob
#define A_4E_C_PPOS_LON_KNB_AM                       0xffff

#define A_4E_C_PRESSURE_RATIO                        0x840a  // Pressure Ratio
#define A_4E_C_PRESSURE_RATIO_AM                     0xffff

#define A_4E_C_RADAR_ALT_INDEX                       0x8510  // Radar Altimeter Warning Knob
#define A_4E_C_RADAR_ALT_INDEX_AM                    0xffff

#define A_4E_C_RADAR_ALT_SW                          0x850e  // Radar Altimeter Warning Button
#define A_4E_C_RADAR_ALT_SW_AM                       0x8000

#define A_4E_C_RADAR_ANGLE                           0x84ee  // Radar Antenna Tilt
#define A_4E_C_RADAR_ANGLE_AM                        0xffff

#define A_4E_C_RADAR_AOACOMP                         0x84ea  // Radar AoA Compensation
#define A_4E_C_RADAR_AOACOMP_AM                      0x0010

#define A_4E_C_RADAR_BRILLIANCE                      0x84f4  // Radar Indicator Brilliance
#define A_4E_C_RADAR_BRILLIANCE_AM                   0xffff

#define A_4E_C_RADAR_DETAIL                          0x84f6  // Radar Indicator Detail
#define A_4E_C_RADAR_DETAIL_AM                       0xffff

#define A_4E_C_RADAR_FILTER                          0x84ea  // Radar Indicator Filter Plate
#define A_4E_C_RADAR_FILTER_AM                       0x0020

#define A_4E_C_RADAR_GAIN                            0x84f8  // Radar Indicator Gain
#define A_4E_C_RADAR_GAIN_AM                         0xffff

#define A_4E_C_RADAR_MODE                            0x84ea  // Radar Mode
#define A_4E_C_RADAR_MODE_AM                         0x000e

#define A_4E_C_RADAR_PROFILE                         0x8500  // Radar Plan/Profile
#define A_4E_C_RADAR_PROFILE_AM                      0x8000

#define A_4E_C_RADAR_RANGE                           0x8502  // Radar Long/Short Range
#define A_4E_C_RADAR_RANGE_AM                        0x0080

#define A_4E_C_RADAR_RETICLE                         0x84fa  // Radar Indicator Reticle
#define A_4E_C_RADAR_RETICLE_AM                      0xffff

#define A_4E_C_RADAR_STORAGE                         0x84f2  // Radar Indicator Storage
#define A_4E_C_RADAR_STORAGE_AM                      0xffff

#define A_4E_C_RADAR_VOL                             0x84f0  // Radar Obstacle Tone Volume
#define A_4E_C_RADAR_VOL_AM                          0xffff

#define A_4E_C_RAIN_REMOVE                           0x8554  // Rain Removal
#define A_4E_C_RAIN_REMOVE_AM                        0x0004

#define A_4E_C_RPM                                   0x8400  // Engine RPM
#define A_4E_C_RPM_AM                                0xffff

#define A_4E_C_RPM_DECI                              0x8402  // Engine RPM DECI
#define A_4E_C_RPM_DECI_AM                           0xffff

#define A_4E_C_RUDDER_TRIM                           0x850c  // Rudder Trim
#define A_4E_C_RUDDER_TRIM_AM                        0xffff

#define A_4E_C_RWR_LIGHT                             0x8470  // Glareshield RWR Light
#define A_4E_C_RWR_LIGHT_AM                          0x0200

#define A_4E_C_SEAT_ADJ                              0x854c  // Seat Adjustment
#define A_4E_C_SEAT_ADJ_AM                           0x3000

#define A_4E_C_SEC_EJECT_HANDLE                      0x8544  // Secondary Ejection Handle
#define A_4E_C_SEC_EJECT_HANDLE_AM                   0x0010

#define A_4E_C_SHRIKE_SEL_KNB                        0x8502  // Shrike Selector Knob
#define A_4E_C_SHRIKE_SEL_KNB_AM                     0x1c00

#define A_4E_C_SPEEDBRAKE                            0x8508  // Speedbrake Switch
#define A_4E_C_SPEEDBRAKE_AM                         0x0400

#define A_4E_C_SPEEDBRAKE_EMERG                      0x8508  // Speedbrake Emergency
#define A_4E_C_SPEEDBRAKE_EMERG_AM                   0x1800

#define A_4E_C_SPOILER_ARM                           0x8508  // Spoiler Arm Switch
#define A_4E_C_SPOILER_ARM_AM                        0x0200

#define A_4E_C_STARTER_BTN                           0x850e  // Starter Button
#define A_4E_C_STARTER_BTN_AM                        0x0004

#define A_4E_C_STBY_ATT_INDEX_BTN                    0x8512  // Standby Attitude Horizon Button
#define A_4E_C_STBY_ATT_INDEX_BTN_AM                 0x0001

#define A_4E_C_STBY_ATT_INDEX_KNB                    0x8514  // Standby Attitude Horizon Knob
#define A_4E_C_STBY_ATT_INDEX_KNB_AM                 0xffff

#define A_4E_C_STOPWATCH                             0x850e  // Stopwatch Start/Stop
#define A_4E_C_STOPWATCH_AM                          0x4000

#define A_4E_C_STOPWATCH_MINS                        0x84e6  // Stopwatch Minutes
#define A_4E_C_STOPWATCH_MINS_AM                     0xffff

#define A_4E_C_STOPWATCH_SECS                        0x84e8  // Stopwatch Seconds
#define A_4E_C_STOPWATCH_SECS_AM                     0xffff

#define A_4E_C_TACAN_ANT_CONT                        0x854c  // TACAN Antenna Control
#define A_4E_C_TACAN_ANT_CONT_AM                     0xc000

#define A_4E_C_TACAN_CHAN_MAJ                        0x8512  // TACAN Channel Major
#define A_4E_C_TACAN_CHAN_MAJ_AM                     0x0780

#define A_4E_C_TACAN_CHAN_MIN                        0x8512  // TACAN Channel Minor
#define A_4E_C_TACAN_CHAN_MIN_AM                     0x7800

#define A_4E_C_TACAN_MODE                            0x8512  // TACAN Mode
#define A_4E_C_TACAN_MODE_AM                         0x0060

#define A_4E_C_TACAN_VOL                             0x8520  // TACAN Volume
#define A_4E_C_TACAN_VOL_AM                          0xffff

#define A_4E_C_THROTTLE_CLICK                        0x850e  // Throttle
#define A_4E_C_THROTTLE_CLICK_AM                     0x0003

#define A_4E_C_VVI                                   0x8448  // Variometer
#define A_4E_C_VVI_AM                                0xffff

#define A_4E_C_WINDSHLD_DEFROST                      0x8544  // Windshield Defrost
#define A_4E_C_WINDSHLD_DEFROST_AM                   0x0006
