[env:dcs_bridge_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
upload_protocol = picotool
monitor_speed = 250000
lib_extra_dirs = ${PROJECT_DIR}/../../Libraries
lib_deps =
    adafruit/Adafruit NeoPixel
    dcs-skunkworks/DCS-BIOS
